dist: trusty
sudo: required

language:
    - c++

install:
    - travis_wait sudo bash scripts/install/install_deps.bash

script:
    - export LD_LIBRARY_PATH=/usr/local/lib
    - git submodule init
    - git submodule update
    - mkdir -p build && cd build && cmake .. && make
    - ./tests/yarl_tests --silence-stdout

notifications:
    recipients:
        - chutsu@gmail.com
    email:
        on_success: change
        on_failure: always
